server:
  port: 9006

picture:
  path:
    processed: D:\data\super-resolution\pic\processed\
    raw: D:\data\super-resolution\pic\raw\

video:
  path:
    processed: D:\data\super-resolution\vid\processed\
    raw: D:\data\super-resolution\vid\raw\


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_resolution?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 300ms
    timeout: 1000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000m

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1



