server:
  port: 9006

python:
  path: C:\Program Files\Python37

picture:
  path:
    processed: D:\data\super-resolution\pic\processed\
    raw: D:\data\super-resolution\pic\raw\

model:
  path:
    image: src/main/resources/model/ESRGAN/imageSR.py
    video: src/main/resources/model/ESRGAN/imageSR.py

video:
  path:
    processed: D:\data\super-resolution\vid\processed\
    raw: D:\data\super-resolution\vid\raw\
    raw_frame: D:\data\super-resolution\vid\raw_frame\
    processed_frame: D:\data\super-resolution\vid\processed_frame\

tool:
  path:
    video2image: src/main/resources/model/TecoGAN/video2image.py
    image2video: src/main/resources/model/TecoGAN/image2video.py



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_resolution?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    connect-timeout: 300ms
    timeout: 1000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000m

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1



