server:
  port: 9006

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_resoluiton?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver



