server:
  port: 9007

picture:
  path:
    processed: file:/data/sr/prod/pic/processed/
    raw: file:/data/sr/prod/pic/raw/

video:
  path:
    processed: file:/data/sr/prod/vid/processed/
    raw: file:/data/sr/prod/vid/raw/

spring:
  datasource:
    url: jdbc:mysql://sr_mysql:3306/super_resoluiton?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ftymgt500.1
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: sr_redis
    port: 6379
    database: 0
    connect-timeout: 300ms
    timeout: 1000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000m

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1



