server:
  port: 9008

picture:
  path:
    processed: /data/sr/test/pic/processed/
    raw: /data/sr/test/pic/raw/

video:
  path:
    processed: /data/sr/test/vid/processed/
    raw: /data/sr/test/vid/raw/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/super_resolution_test?useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: ftymgt500.1
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    connect-timeout: 300ms
    timeout: 1000ms
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: 1000m

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1



